server:
  port: 9190
spring:
  application:
    name: PRODUCT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "com.ecommerce.ProductService.model.v1"
  instance:
    hostname: localhost

